env:
  browser: true
  es2021: true
extends:
  - standard
  # - standard-with-typescript
  # - plugin:react/recommended
  # - plugin:react-hooks/recommended
  # - plugin:typescript-sort-keys/recommended
  - prettier
# parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    js: true
    jsx: true
    ts: true
    tsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - prettier
#   # https://github.com/yannickcr/eslint-plugin-react
#   - react
#   # https://www.npmjs.com/package/eslint-plugin-react-hooks
#   - react-hooks
#   # https://github.com/benmosher/eslint-plugin-import
#   - import
#   # https://github.com/typescript-eslint/typescript-eslint
#   - "@typescript-eslint"
#   # https://github.com/infctr/eslint-plugin-typescript-sort-keys
#   - typescript-sort-keys
# # https://github.com/jambit/eslint-plugin-typed-redux-saga
# - "@jambit/typed-redux-saga"
overrides:
  - files:
      - './**/*.+(ts|js|tsx|jsx)'
    rules:
      'prettier/prettier': 2
      # 'no-redeclare': 0
      # 'no-undef': 0
      # 'no-unused-vars': 0
      # 'max-len': [2, {code: 130}]
      # 'no-useless-constructor': 0
      # 'comma-dangle': 0
      # 'no-dupe-class-members': 0
      'semi': [2, 'always']
      # 'indent': 0
      # 'newline-before-return': 2
      # 'no-fallthrough': 0
      # 'padded-blocks': [2, {'classes': 'always'}]
      # 'import/order':
      #   [
      #     2,
      #     {
      #       'alphabetize': {'order': 'asc', 'caseInsensitive': true},
      #       'warnOnUnassignedImports': true,
      #       'newlines-between': 'always',
      #     },
      #   ]
      # 'import/newline-after-import': [2, {'count': 1}]
      # - 2
      # - blocks: never
      #   classes: never
      #   switches: never

      # typescript
      # "@typescript-eslint/indent": [2, 2]
      # "@typescript-eslint/type-annotation-spacing": 2
      # "@typescript-eslint/comma-dangle": [2, "always-multiline"]
      # "typescript-sort-keys/interface": [2, "asc", { requiredFirst: true }]
      # "@typescript-eslint/member-delimiter-style": 2

      # react
      # "react/self-closing-comp": 2
      # "react/no-children-prop": 0
      # "react/jsx-props-no-multi-spaces": 2
      # "react/jsx-tag-spacing": 2
      # "react/jsx-equals-spacing": 2
      # "react/jsx-curly-spacing": 2
      # "react/jsx-sort-props": 2
      # "react/jsx-wrap-multilines": 2
      # "react/jsx-indent-props": [2, 2]
      # "react/jsx-first-prop-new-line": 2
      # "react/jsx-max-props-per-line": [2, { "maximum": 1, "when": "multiline" }]
      # "react/jsx-closing-tag-location": 2
      # "react/jsx-closing-bracket-location": [2, "line-aligned"]
      # "react/jsx-indent":
      #   [2, 2, { "checkAttributes": true, "indentLogicalExpressions": true }]
      # "react/jsx-curly-brace-presence":
      #   [
      #     2,
      #     {
      #       "props": "always",
      #       "children": "never",
      #       "propElementValues": "always",
      #     },
      #   ]
  # - files:
  #     - "./**/*.+(ts|js|tsx|jsx)"
  #   excludedFiles:
  #     - "./**/*.spec.ts"
  #   rules:
  #     "@jambit/typed-redux-saga/use-typed-effects": error
  #     "@jambit/typed-redux-saga/delegate-effects": error
