printWidth: 120
useTabs: false
semi: true
singleQuote: true
quoteProps: as-needed
jsxSingleQuote: true
trailingComma: all
bracketSpacing: false
bracketSameLine: false
arrowParens: always
endOfLine: lf
